ekf_se_odom:   # Used only for broadcasting odom to base_link transforms
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true  # false true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: false
  debug: false
  debug_out_file: /path/to/debug/file.txt
  publish_tf: true
  publish_acceleration: false


  map_frame: map
  odom_frame: odom
  base_link_frame: base_footprint 
  world_frame: odom


#  The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. -->

# -------------------------------------
# Wheel odometry:
  odom0: /odom  
  # odom0_config: [false, false, true,  #  x, y, z
  #                false, false, false,  #  roll, pitch, yaw
  #                true,  true,  true,   #  vx, vy, vz,
  #                false, false, true,   #  vroll, vpitch, vyaw,
  #                false, false, false]  #  ax, ay, az
  odom0_config: [false, false, false,  #  x, y, z
                 false, false, false,  #  roll, pitch, yaw
                 true,  true, false,   #  vx, vy, vz,
                 false, false, false,   #  vroll, vpitch, vyaw,
                 false, false, false]  #  ax, ay, az
  odom0_queue_size: 5
  odom0_nodelay: false
  odom0_differential: false
  odom0_relative: false


# --------------------------------------
# imu configure:

  imu0: /imu/data  # /imu/data     # sullivan /imu_republish
  # imu0_config: [false, false, false,  #  x, y, z
  #               true,  true,  true,  #  roll, pitch, yaw
  #               false, false, false,  #  vx, vy, vz,
  #               true,  true,  true,   #  vroll, vpitch, vyaw,
                # false,  false,  false]   #  ax, ay, az
  imu0_config: [false, false, false,  #  x, y, z
                false,  false,  false,  #  roll, pitch, yaw
                false, false, false,  #  vx, vy, vz,
                false, false, true, #  vroll, vpitch, vyaw,
                false,  false,  false]   #  ax, ay, az
                
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 5
  # imu0_remove_gravitational_acceleration: true

  use_control: false  # false
  stamped_control: false
  control_timeout: 0.2
  control_config: [true, false, false,  #  vx, vy, vz,
                  false,  false,  true]  #  vroll, vpitch, vyaw,
 
  # Places limits on how large the acceleration term will be. Should match your robot's kinematics.
  acceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.2]
  # Acceleration and deceleration limits are not always the same for robots.
  deceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.2]
  # If your robot cannot instantaneously reach its acceleration limit, the permitted change can be controlled with these
  # gains
  acceleration_gains: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  # If your robot cannot instantaneously reach its deceleration limit, the permitted change can be controlled with these
  # gains
  deceleration_gains: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]
  
  initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    1e-9,  0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    1e-9,  0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    1e-9,  0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    1e-9,  0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,   0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,   0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,   0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9,  0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9,  0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]
