set(_CATKIN_CURRENT_PACKAGE "mars_lite_description")
set(mars_lite_description_VERSION "1.0.0")
set(mars_lite_description_MAINTAINER "Josuet Leoro <josuet.leoro@itri.org.tw>")
set(mars_lite_description_PACKAGE_FORMAT "2")
set(mars_lite_description_BUILD_DEPENDS "urdf")
set(mars_lite_description_BUILD_EXPORT_DEPENDS "urdf")
set(mars_lite_description_BUILDTOOL_DEPENDS "catkin")
set(mars_lite_description_BUILDTOOL_EXPORT_DEPENDS )
set(mars_lite_description_EXEC_DEPENDS "urdf")
set(mars_lite_description_RUN_DEPENDS "urdf")
set(mars_lite_description_TEST_DEPENDS )
set(mars_lite_description_DOC_DEPENDS )
set(mars_lite_description_URL_WEBSITE "")
set(mars_lite_description_URL_BUGTRACKER "")
set(mars_lite_description_URL_REPOSITORY "")
set(mars_lite_description_DEPRECATED "")