#Some important paths
FileDir: /home/berlin/lab
mapsDir: /socially-store-robot/mars_ws/src/navigation/turtlebot3_navigation/maps/
sceneDir: /socially-store-robot/mars_ws/src/pedsim_ros/pedsim_simulator/scenarios/
#docker
Docker:
  Enabled: true
  ContainerName: berlinjiang/flexiable_social_navigation:cohan_navigation_testing
  RunCmd: source docker_run.sh 
  ExecCmd: source docker_run.sh
##############
#The launch file you want to launch in order
# {curSceneItem} is used for rviz visualize scenes.
# {curMapItem} is used for gazebo scenes.
# {robot_x}, {robot_y}, {robot_rot} is for robot
LaunchItems:
  gazebo:
    Enabled: true
    Delay: 3
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch pedsim_gazebo_plugin {curMapItem}.launch
  robot:
    Enabled: true
    Delay: 2
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch mars_lite_description spawn_mars.launch robot_init_x:={robot_x} robot_init_y:={robot_y} robot_init_rot:={robot_rot}
  pedsim:
    Enabled: true
    Delay: 0 
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch pedsim_simulator shopping_mall.launch scene_file:={curSceneItem}.xml 
  globalmap:
    Enabled: false
    Delay: 2
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch turtlebot3_navigation globalmap.launch map_file:={curMapItem}.yaml
  yolo:
    Enabled: false
    Delay: 1
    Workspace: socially-store-robot/yolo_ws
    Command: roslaunch scan yolodetect.launch
  nav(cohan):
    Enabled: true
    Delay: 2
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch cohan_navigation nav_cohan.launch map_file:={curMapItem}.yaml
  nav(move_base):
    Enabled: false
    Delay: 2
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch turtlebot3_navigation move_base.launch
  nav(social):
    Enabled: false
    Delay: 10
    Workspace: socially-store-robot/yolo_ws
    Command: roslaunch path_finding socially_navigation.launch
  initRobotInRviz:
    Enabled: true
    Delay: 5
    Workspace: socially-store-robot/mars_ws
    Command: roslaunch mars_lite_description init_pose.launch robot_init_x:={robot_x} robot_init_y:={robot_y} robot_init_rot:={robot_rot}
  

######################
AlignWindows:
  - Name: Gazebo
    X: 960
    Y: 0
    Width: 960
    Height: 1080
  - Name: Rviz
    X: 0
    Y: 540
    Width: 960
    Height: 540
  - Name: Yolo demo
    X: 0
    Y: 0
    Width: 960
    Height: 540
