footprint: [[-0.35, -0.3], [-0.35, 0.3], [0.65, 0.3], [0.65, -0.3]]
#robot_radius: 0.105

map_type: costmap

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 3.5
 footprint_clearing_enabled: true
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, sensor_frame: merged_laser_frame, topic: /scan, marking: true, clearing: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.35  # max. distance from an obstacle at which costs are incurred for planning paths.


static_layer:
  enabled:              true
  map_topic:            "/map"