displayed_costmap: 
  # ootprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
  # #robot_radius: 0.105

  # map_type: costmap

  # always_send_full_costmap: true

  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.8
  
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: human_layer_static, type: "human_layers::StaticHumanLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
      
  static_layer:
    enabled:              true
    map_topic:            "/map"

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.35

  obstacle_layer:
    enabled: true
    obstacle_range: 3.0
    raytrace_range: 3.5
    footprint_clearing_enabled: true
    track_unknown_space: true
    combination_method: 1

    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, sensor_frame: merged_laser_frame, topic: /scan, marking: true, clearing: true}

