global_costmap:
  publish_frequency: 10.0
  update_frequency: 10.0
  transform_tolerance: 0.8
  global_frame: map
  robot_base_frame: base_footprint
  rolling_window: false

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  inflation_layer:
    enabled:              true
    cost_scaling_factor:  3.0  
    inflation_radius:     0.9


